#!/bin/bash
declare -A DBSETTINGS

################ Only changes go here
DBSETTINGS["DBHOST"]="localhost"
DBSETTINGS["DBUSER"]="root"
DBSETTINGS["DBPASS"]="admin"
#####################################
